# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/FIR/FIR/FIR.xci
# IP: The module: 'FIR' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/FIR/FIR/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/FIR/FIR/FIR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/FIR/FIR/FIR.xci
# IP: The module: 'FIR' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/FIR/FIR/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/FIR/FIR/FIR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
