# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Workspace/Vivado_16.4/2018_1_20_AM/AM.cache/wt [current_project]
set_property parent.project_path E:/Workspace/Vivado_16.4/2018_1_20_AM/AM.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Workspace/Vivado_16.4/2018_1_20_AM/AM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/cos_8_1024_signed.coe
add_files -quiet e:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/ROM/ROM/ROM.dcp
set_property used_in_implementation false [get_files e:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/ROM/ROM/ROM.dcp]
read_verilog -library xil_defaultlib E:/Workspace/Vivado_16.4/2018_1_20_AM/Design/Code/cos_make.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top cos_make -part xc7a35tcpg236-1


write_checkpoint -force -noxdef cos_make.dcp

catch { report_utilization -file cos_make_utilization_synth.rpt -pb cos_make_utilization_synth.pb }
