# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/MULT/MULT/MULT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MULT || ORIG_REF_NAME==MULT}]
