# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Workspace/Vivado_16.4/2018_1_20_AM/AM.cache/wt [current_project]
set_property parent.project_path E:/Workspace/Vivado_16.4/2018_1_20_AM/AM.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Workspace/Vivado_16.4/2018_1_20_AM/AM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/cos_8_1024_signed.coe
add_files -quiet e:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/ROM/ROM/ROM.dcp
set_property used_in_implementation false [get_files e:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/ROM/ROM/ROM.dcp]
read_verilog -library xil_defaultlib {
  E:/Workspace/Vivado_16.4/2018_1_20_AM/Design/Code/modulate.v
  E:/Workspace/Vivado_16.4/2018_1_20_AM/Design/Code/cos_make.v
  E:/Workspace/Vivado_16.4/2018_1_20_AM/Design/Code/TOP.v
}
read_ip -quiet E:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/MULT/MULT/MULT.xci
set_property used_in_implementation false [get_files -all e:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/MULT/MULT/MULT_ooc.xdc]
set_property is_locked true [get_files E:/Workspace/Vivado_16.4/2018_1_20_AM/Design/IP_Core/MULT/MULT/MULT.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top TOP -part xc7a35tcpg236-1


write_checkpoint -force -noxdef TOP.dcp

catch { report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb }
